### ISSUE TITLE
Change how 'gams clean' and 'madara clean' are interpreted by base_build.sh to better reflect user intent

### ISSUE THREAD

**Issue by TheDash** [jredmondson/gams#66]
I've been thinking - This is a petition to change ./base_build.sh default functionality for the 'gams' keyword to implicitly include the madara keyword. 

This would prevent the linker errors that arise when running 'base_build.sh gams' after doing a clean. Users who want madara stand alone can run 'base_build.sh madara' and those who want gams shouldn't also need to write 'base_build.sh gams c++ boost pthread eigen' etc if you catch my drift.

Small issue, pretty trivial and yes it may seem side tracking but I'm in the code modifying this stuff so would be an easy addition. 

My reason: After doing a 'base_build.sh gams airlib clean' my linker spit out a bunch of errors and even I was confused because that wasn't my intent to have to rebuild MADARA. Only GAMS. Change would mean we could clean madara clean and gams clean separately rather than altogether. 

E.g proposed functionality:

(1) ./base_build.sh gams clean  [rebuilds gams only]
(2) ./base_build.sh madara clean [rebuilds both gams and madara, as gams is prereq]
(3) ./base_build.sh clean [builds both]

The users intent for (1) is definitely not to clean madara and re-compile gams, which they will end up with linker errors if they do this.

**Comment by jredmondson** [comment]
So, I do like making madara a prereq of gams if it isn't built (which is how things are currently done), and I also like the ability to specify exactly what components I want to build. However, I do understand that we could make things easier.

Right now, we remember the last build that didn't use "noclean". If we parse this file, we could make a more intelligent way for base_build.sh to figure out if madara and all dependencies have to be rebuilt. The most obvious instance is when you have to switch between gams with clang or gamswith g++. If you do that, you basically need to rebuild the dependencies that have to have the appropriate symbols. So, I think the best way to approach this is not to force the clean keyword but to instead look at the last "noclean" build and see if any of the new keywords require all prereqs to be rebuilt. I know clang/g++ will cause this. Really, anything that changes the preprocessor symbols could also use this kind of intelligence to make things straight forward. Will think about this.

**Comment by jredmondson** [comment]
So, I  have updated the action.sh script to automatically use "clang" if clang was used on the base_build.sh in Linux. I've also added noclean option and make depend to produce faster/better compilation with noclean. The action.sh now also has the last_build.lst feature where it remembers your last build and you can call "./action.sh" with no arguments to repeat the last build with "noclean".

Think about what else your issue is trying to address here. I know this solves my issue of accidentally compiling with g++ in action.sh when I actually used clang in base_build.sh. Are we good here?

**Comment by jredmondson** [comment]
Additional updates on the base_build.sh process are that we now save the environment variables for users in the $HOME/.gams/env.sh file, and we also record all previous builds in $HOME/.gams/builds.lst so people can copy/paste old builds that they may have forgotten all the keywords to.

I actually ran $GAMS_ROOT/scripts/linux/base_build.sh with just gams and it did not force a clean of madara. Should this issue still be active or is it ok to close it?

**Comment by jredmondson** [comment]
I think I've fixed all issues related to this. MADARA and GAMS will both be rebuilt if you switch between clang and g++ now (assuming you have had a successful build before as it checks last_build.lst). To get rebuilds of capnp and eigen, you'd need to do prereqs also, but I think that's a reasonable requirement.

https://github.com/jredmondson/gams/commit/2e656b0c85804f4dbd8e031d2778f2c920807595

If you don't have any additional requests, I'll be closing out this issue.

**Comment by TheDash** [comment]
Woot =) I think that is definitely expected behavior and will prevent compiler errors for new users and existing users alike!

**Comment by jredmondson** [comment]
Closing!
